/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialRouteImport } from './routes/testimonial'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as UserAuthRouteImport } from './routes/user.auth'
import { Route as ProjectSubmitRouteImport } from './routes/project.submit'
import { Route as ProjectListRouteImport } from './routes/project.list'
import { Route as ProjectSlugRouteImport } from './routes/project.$slug'
import { Route as EventListRouteImport } from './routes/event.list'
import { Route as EventSlugRouteImport } from './routes/event.$slug'
import { Route as DashboardPostsRouteImport } from './routes/dashboard.posts'
import { Route as BlogEditorRouteImport } from './routes/blog.editor'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiYoutubeRouteImport } from './routes/api/youtube'
import { Route as ApiVibeVideosRouteImport } from './routes/api/vibe-videos'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as ApiGithubImportRouteImport } from './routes/api/github-import'
import { Route as ApiAuthCheckRouteImport } from './routes/api/auth-check'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as BlogEditorIndexRouteImport } from './routes/blog.editor.index'
import { Route as UserAuthResetPasswordRouteImport } from './routes/user.auth.reset-password'
import { Route as UserAuthConfirmEmailRouteImport } from './routes/user.auth.confirm-email'
import { Route as BlogEditorSlugRouteImport } from './routes/blog.editor.$slug'
import { Route as ApiVibeVideosIdRouteImport } from './routes/api/vibe-videos.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiAiEnhanceDescriptionRouteImport } from './routes/api/ai.enhance-description'
import { Route as ApiAiCompletionRouteImport } from './routes/api/ai.completion'

const TestimonialRoute = TestimonialRouteImport.update({
  id: '/testimonial',
  path: '/testimonial',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const UserAuthRoute = UserAuthRouteImport.update({
  id: '/user/auth',
  path: '/user/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSubmitRoute = ProjectSubmitRouteImport.update({
  id: '/project/submit',
  path: '/project/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectListRoute = ProjectListRouteImport.update({
  id: '/project/list',
  path: '/project/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventListRoute = EventListRouteImport.update({
  id: '/event/list',
  path: '/event/list',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugRoute = EventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPostsRoute = DashboardPostsRouteImport.update({
  id: '/dashboard/posts',
  path: '/dashboard/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogEditorRoute = BlogEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiYoutubeRoute = ApiYoutubeRouteImport.update({
  id: '/api/youtube',
  path: '/api/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVibeVideosRoute = ApiVibeVideosRouteImport.update({
  id: '/api/vibe-videos',
  path: '/api/vibe-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubImportRoute = ApiGithubImportRouteImport.update({
  id: '/api/github-import',
  path: '/api/github-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCheckRoute = ApiAuthCheckRouteImport.update({
  id: '/api/auth-check',
  path: '/api/auth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BlogEditorIndexRoute = BlogEditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogEditorRoute,
} as any)
const UserAuthResetPasswordRoute = UserAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => UserAuthRoute,
} as any)
const UserAuthConfirmEmailRoute = UserAuthConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => UserAuthRoute,
} as any)
const BlogEditorSlugRoute = BlogEditorSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogEditorRoute,
} as any)
const ApiVibeVideosIdRoute = ApiVibeVideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiVibeVideosRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiEnhanceDescriptionRoute = ApiAiEnhanceDescriptionRouteImport.update({
  id: '/api/ai/enhance-description',
  path: '/api/ai/enhance-description',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCompletionRoute = ApiAiCompletionRouteImport.update({
  id: '/api/ai/completion',
  path: '/api/ai/completion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/testimonial': typeof TestimonialRoute
  '/dashboard': typeof AdminDashboardRoute
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/github-import': typeof ApiGithubImportRoute
  '/api/og': typeof ApiOgRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/vibe-videos': typeof ApiVibeVideosRouteWithChildren
  '/api/youtube': typeof ApiYoutubeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/editor': typeof BlogEditorRouteWithChildren
  '/dashboard/posts': typeof DashboardPostsRoute
  '/event/$slug': typeof EventSlugRoute
  '/event/list': typeof EventListRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/project/list': typeof ProjectListRoute
  '/project/submit': typeof ProjectSubmitRoute
  '/user/auth': typeof UserAuthRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/api/ai/completion': typeof ApiAiCompletionRoute
  '/api/ai/enhance-description': typeof ApiAiEnhanceDescriptionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/vibe-videos/$id': typeof ApiVibeVideosIdRoute
  '/blog/editor/$slug': typeof BlogEditorSlugRoute
  '/user/auth/confirm-email': typeof UserAuthConfirmEmailRoute
  '/user/auth/reset-password': typeof UserAuthResetPasswordRoute
  '/blog/editor/': typeof BlogEditorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/testimonial': typeof TestimonialRoute
  '/dashboard': typeof AdminDashboardRoute
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/github-import': typeof ApiGithubImportRoute
  '/api/og': typeof ApiOgRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/vibe-videos': typeof ApiVibeVideosRouteWithChildren
  '/api/youtube': typeof ApiYoutubeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/posts': typeof DashboardPostsRoute
  '/event/$slug': typeof EventSlugRoute
  '/event/list': typeof EventListRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/project/list': typeof ProjectListRoute
  '/project/submit': typeof ProjectSubmitRoute
  '/user/auth': typeof UserAuthRouteWithChildren
  '/blog': typeof BlogIndexRoute
  '/api/ai/completion': typeof ApiAiCompletionRoute
  '/api/ai/enhance-description': typeof ApiAiEnhanceDescriptionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/vibe-videos/$id': typeof ApiVibeVideosIdRoute
  '/blog/editor/$slug': typeof BlogEditorSlugRoute
  '/user/auth/confirm-email': typeof UserAuthConfirmEmailRoute
  '/user/auth/reset-password': typeof UserAuthResetPasswordRoute
  '/blog/editor': typeof BlogEditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/$username': typeof UsernameRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/testimonial': typeof TestimonialRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/github-import': typeof ApiGithubImportRoute
  '/api/og': typeof ApiOgRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/vibe-videos': typeof ApiVibeVideosRouteWithChildren
  '/api/youtube': typeof ApiYoutubeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/editor': typeof BlogEditorRouteWithChildren
  '/dashboard/posts': typeof DashboardPostsRoute
  '/event/$slug': typeof EventSlugRoute
  '/event/list': typeof EventListRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/project/list': typeof ProjectListRoute
  '/project/submit': typeof ProjectSubmitRoute
  '/user/auth': typeof UserAuthRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/api/ai/completion': typeof ApiAiCompletionRoute
  '/api/ai/enhance-description': typeof ApiAiEnhanceDescriptionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/vibe-videos/$id': typeof ApiVibeVideosIdRoute
  '/blog/editor/$slug': typeof BlogEditorSlugRoute
  '/user/auth/confirm-email': typeof UserAuthConfirmEmailRoute
  '/user/auth/reset-password': typeof UserAuthResetPasswordRoute
  '/blog/editor/': typeof BlogEditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/admin'
    | '/blog'
    | '/calendar'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/terms-of-service'
    | '/testimonial'
    | '/dashboard'
    | '/api/auth-check'
    | '/api/github-import'
    | '/api/og'
    | '/api/uploadthing'
    | '/api/vibe-videos'
    | '/api/youtube'
    | '/blog/$slug'
    | '/blog/editor'
    | '/dashboard/posts'
    | '/event/$slug'
    | '/event/list'
    | '/project/$slug'
    | '/project/list'
    | '/project/submit'
    | '/user/auth'
    | '/blog/'
    | '/api/ai/completion'
    | '/api/ai/enhance-description'
    | '/api/auth/$'
    | '/api/vibe-videos/$id'
    | '/blog/editor/$slug'
    | '/user/auth/confirm-email'
    | '/user/auth/reset-password'
    | '/blog/editor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/admin'
    | '/calendar'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/terms-of-service'
    | '/testimonial'
    | '/dashboard'
    | '/api/auth-check'
    | '/api/github-import'
    | '/api/og'
    | '/api/uploadthing'
    | '/api/vibe-videos'
    | '/api/youtube'
    | '/blog/$slug'
    | '/dashboard/posts'
    | '/event/$slug'
    | '/event/list'
    | '/project/$slug'
    | '/project/list'
    | '/project/submit'
    | '/user/auth'
    | '/blog'
    | '/api/ai/completion'
    | '/api/ai/enhance-description'
    | '/api/auth/$'
    | '/api/vibe-videos/$id'
    | '/blog/editor/$slug'
    | '/user/auth/confirm-email'
    | '/user/auth/reset-password'
    | '/blog/editor'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/$username'
    | '/admin'
    | '/blog'
    | '/calendar'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/terms-of-service'
    | '/testimonial'
    | '/_admin/dashboard'
    | '/api/auth-check'
    | '/api/github-import'
    | '/api/og'
    | '/api/uploadthing'
    | '/api/vibe-videos'
    | '/api/youtube'
    | '/blog/$slug'
    | '/blog/editor'
    | '/dashboard/posts'
    | '/event/$slug'
    | '/event/list'
    | '/project/$slug'
    | '/project/list'
    | '/project/submit'
    | '/user/auth'
    | '/blog/'
    | '/api/ai/completion'
    | '/api/ai/enhance-description'
    | '/api/auth/$'
    | '/api/vibe-videos/$id'
    | '/blog/editor/$slug'
    | '/user/auth/confirm-email'
    | '/user/auth/reset-password'
    | '/blog/editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  UsernameRoute: typeof UsernameRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TestimonialRoute: typeof TestimonialRoute
  ApiAuthCheckRoute: typeof ApiAuthCheckRoute
  ApiGithubImportRoute: typeof ApiGithubImportRoute
  ApiOgRoute: typeof ApiOgRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ApiVibeVideosRoute: typeof ApiVibeVideosRouteWithChildren
  ApiYoutubeRoute: typeof ApiYoutubeRoute
  DashboardPostsRoute: typeof DashboardPostsRoute
  EventSlugRoute: typeof EventSlugRoute
  EventListRoute: typeof EventListRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
  ProjectListRoute: typeof ProjectListRoute
  ProjectSubmitRoute: typeof ProjectSubmitRoute
  UserAuthRoute: typeof UserAuthRouteWithChildren
  ApiAiCompletionRoute: typeof ApiAiCompletionRoute
  ApiAiEnhanceDescriptionRoute: typeof ApiAiEnhanceDescriptionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonial': {
      id: '/testimonial'
      path: '/testimonial'
      fullPath: '/testimonial'
      preLoaderRoute: typeof TestimonialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/user/auth': {
      id: '/user/auth'
      path: '/user/auth'
      fullPath: '/user/auth'
      preLoaderRoute: typeof UserAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/submit': {
      id: '/project/submit'
      path: '/project/submit'
      fullPath: '/project/submit'
      preLoaderRoute: typeof ProjectSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/list': {
      id: '/project/list'
      path: '/project/list'
      fullPath: '/project/list'
      preLoaderRoute: typeof ProjectListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/list': {
      id: '/event/list'
      path: '/event/list'
      fullPath: '/event/list'
      preLoaderRoute: typeof EventListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$slug': {
      id: '/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof EventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/posts': {
      id: '/dashboard/posts'
      path: '/dashboard/posts'
      fullPath: '/dashboard/posts'
      preLoaderRoute: typeof DashboardPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/editor': {
      id: '/blog/editor'
      path: '/editor'
      fullPath: '/blog/editor'
      preLoaderRoute: typeof BlogEditorRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/youtube': {
      id: '/api/youtube'
      path: '/api/youtube'
      fullPath: '/api/youtube'
      preLoaderRoute: typeof ApiYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vibe-videos': {
      id: '/api/vibe-videos'
      path: '/api/vibe-videos'
      fullPath: '/api/vibe-videos'
      preLoaderRoute: typeof ApiVibeVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-import': {
      id: '/api/github-import'
      path: '/api/github-import'
      fullPath: '/api/github-import'
      preLoaderRoute: typeof ApiGithubImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-check': {
      id: '/api/auth-check'
      path: '/api/auth-check'
      fullPath: '/api/auth-check'
      preLoaderRoute: typeof ApiAuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/blog/editor/': {
      id: '/blog/editor/'
      path: '/'
      fullPath: '/blog/editor/'
      preLoaderRoute: typeof BlogEditorIndexRouteImport
      parentRoute: typeof BlogEditorRoute
    }
    '/user/auth/reset-password': {
      id: '/user/auth/reset-password'
      path: '/reset-password'
      fullPath: '/user/auth/reset-password'
      preLoaderRoute: typeof UserAuthResetPasswordRouteImport
      parentRoute: typeof UserAuthRoute
    }
    '/user/auth/confirm-email': {
      id: '/user/auth/confirm-email'
      path: '/confirm-email'
      fullPath: '/user/auth/confirm-email'
      preLoaderRoute: typeof UserAuthConfirmEmailRouteImport
      parentRoute: typeof UserAuthRoute
    }
    '/blog/editor/$slug': {
      id: '/blog/editor/$slug'
      path: '/$slug'
      fullPath: '/blog/editor/$slug'
      preLoaderRoute: typeof BlogEditorSlugRouteImport
      parentRoute: typeof BlogEditorRoute
    }
    '/api/vibe-videos/$id': {
      id: '/api/vibe-videos/$id'
      path: '/$id'
      fullPath: '/api/vibe-videos/$id'
      preLoaderRoute: typeof ApiVibeVideosIdRouteImport
      parentRoute: typeof ApiVibeVideosRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/enhance-description': {
      id: '/api/ai/enhance-description'
      path: '/api/ai/enhance-description'
      fullPath: '/api/ai/enhance-description'
      preLoaderRoute: typeof ApiAiEnhanceDescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/completion': {
      id: '/api/ai/completion'
      path: '/api/ai/completion'
      fullPath: '/api/ai/completion'
      preLoaderRoute: typeof ApiAiCompletionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface BlogEditorRouteChildren {
  BlogEditorSlugRoute: typeof BlogEditorSlugRoute
  BlogEditorIndexRoute: typeof BlogEditorIndexRoute
}

const BlogEditorRouteChildren: BlogEditorRouteChildren = {
  BlogEditorSlugRoute: BlogEditorSlugRoute,
  BlogEditorIndexRoute: BlogEditorIndexRoute,
}

const BlogEditorRouteWithChildren = BlogEditorRoute._addFileChildren(
  BlogEditorRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogEditorRoute: typeof BlogEditorRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogEditorRoute: BlogEditorRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ApiVibeVideosRouteChildren {
  ApiVibeVideosIdRoute: typeof ApiVibeVideosIdRoute
}

const ApiVibeVideosRouteChildren: ApiVibeVideosRouteChildren = {
  ApiVibeVideosIdRoute: ApiVibeVideosIdRoute,
}

const ApiVibeVideosRouteWithChildren = ApiVibeVideosRoute._addFileChildren(
  ApiVibeVideosRouteChildren,
)

interface UserAuthRouteChildren {
  UserAuthConfirmEmailRoute: typeof UserAuthConfirmEmailRoute
  UserAuthResetPasswordRoute: typeof UserAuthResetPasswordRoute
}

const UserAuthRouteChildren: UserAuthRouteChildren = {
  UserAuthConfirmEmailRoute: UserAuthConfirmEmailRoute,
  UserAuthResetPasswordRoute: UserAuthResetPasswordRoute,
}

const UserAuthRouteWithChildren = UserAuthRoute._addFileChildren(
  UserAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  UsernameRoute: UsernameRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRouteWithChildren,
  CalendarRoute: CalendarRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TestimonialRoute: TestimonialRoute,
  ApiAuthCheckRoute: ApiAuthCheckRoute,
  ApiGithubImportRoute: ApiGithubImportRoute,
  ApiOgRoute: ApiOgRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ApiVibeVideosRoute: ApiVibeVideosRouteWithChildren,
  ApiYoutubeRoute: ApiYoutubeRoute,
  DashboardPostsRoute: DashboardPostsRoute,
  EventSlugRoute: EventSlugRoute,
  EventListRoute: EventListRoute,
  ProjectSlugRoute: ProjectSlugRoute,
  ProjectListRoute: ProjectListRoute,
  ProjectSubmitRoute: ProjectSubmitRoute,
  UserAuthRoute: UserAuthRouteWithChildren,
  ApiAiCompletionRoute: ApiAiCompletionRoute,
  ApiAiEnhanceDescriptionRoute: ApiAiEnhanceDescriptionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
