import { createRpcAction } from '@/lib/rpc-client'

export const signIn = createRpcAction('actions.signIn')
export const signUp = createRpcAction('actions.signUp')
export const signOut = createRpcAction('actions.signOut')
export const resetPassword = createRpcAction('actions.resetPassword')
export const resendConfirmationEmail = createRpcAction('actions.resendConfirmationEmail')
export const getProjectBySlug = createRpcAction('actions.getProjectBySlug')
export const getProject = createRpcAction('actions.getProject')
export const incrementProjectViews = createRpcAction('actions.incrementProjectViews')
export const incrementBlogPostViews = createRpcAction('actions.incrementBlogPostViews')
export const toggleLike = createRpcAction('actions.toggleLike')
export const getLikeStatus = createRpcAction('actions.getLikeStatus')
export const signInWithGoogle = createRpcAction('actions.signInWithGoogle')
export const signInWithGitHub = createRpcAction('actions.signInWithGitHub')
export const getBatchLikeStatus = createRpcAction('actions.getBatchLikeStatus')
export const editProject = createRpcAction('actions.editProject')
export const fetchProjectsWithSorting = createRpcAction('actions.fetchProjectsWithSorting')
export const deleteProject = createRpcAction('actions.deleteProject')
